# Hand-designed column layouts: id (without VIE_) -> (local x, rank). Column centres are set in unify.py.
M1 = {  # army (Col 1, center X = 59)
    'tank_modernization': (0, 1),
    'rocket_artillery': (-3, 2), 'mechanization': (-1, 2), 't90_tanks': (1, 2), 'special_forces': (3, 2),
    'corps_restructure': (3, 3),
    'reserve_mobilization': (1, 4),
    'army_development': (0, 6),
    'army_nco_corps': (-4, 7), 'army_combined_arms': (0, 7),
    'army_military_regions': (-4, 8), 'path_peoples_war': (-2, 8), 'army_expeditionary': (0, 8), 'army_jungle_warfare': (2, 8),
    'army_mech_corps': (-6, 9), 'army_combat_engineers': (-4, 9), 'army_dan_quan_modern': (-2, 9), 'army_logistics_reform': (-1, 9),
    'army_academies': (-5, 10), 'army_underground_bases': (-2, 10), 'army_iron_triangle': (1, 10),
    'army_border_guard_corps': (-3, 11), 'army_sp_artillery': (-1, 11), 'army_short_range_ad': (1, 11), 'army_armor_modernization': (3, 11), 'army_exp_brigades': (5, 11),
    'army_electronic_warfare': (0, 12), 'army_night_optics': (2, 12), 'army_exp_hubs': (5, 12),
    'army_c4isr': (1, 13), 'army_intervention_force': (5, 13),
    'army_vpa_2030': (3, 14),
}
M2 = {  # navy (Col 2, center X = 73)
    'navy_modernization': (0, 1),
    'naval_aviation': (-6, 2), 'kilo_submarines': (-4, 2), 'gepard_frigates': (-2, 2), 'bastion_p_coastal_defence': (0, 2),
    'domestic_corvettes': (2, 2), 'domestic_antiship': (4, 2), 'naval_infantry': (6, 2),
    'cam_ranh_base': (-2, 3),
    'cam_ranh_port_diplomacy': (0, 4),
    'navy_development': (0, 6),
    'navy_naval_regions': (-4, 7), 'navy_fleet_training': (0, 7),
    'navy_naval_academy': (-4, 8), 'path_maritime_denial': (-2, 8), 'navy_blue_water': (2, 8),
    'navy_hydrography': (-5, 9), 'navy_marines': (-3, 9), 'navy_asw_capacity': (-1, 9), 'navy_forward_basing': (1, 9),
    'navy_coast_guard': (-4, 10), 'navy_sea_control': (0, 10),
    'navy_missile_boats': (-3, 11), 'navy_sub_base': (-1, 11), 'navy_asw_helicopters': (1, 11),
    'navy_ba_son': (-4, 12), 'navy_coastal_sensors': (-2, 12), 'navy_island_network': (0, 12), 'navy_blue_destroyers': (2, 12),
    'navy_submarine_expansion': (-3, 13), 'navy_replenishment': (2, 13),
    'navy_usv_uuv': (-2, 14), 'navy_light_carrier': (2, 14),
    'navy_spratly_fleet': (1, 15),
    'navy_vn_navy_2030': (-1, 16),
}
M3 = {  # air (Col 3, center X = 87)
    'air_force_modernization': (0, 1),
    'su30mk2_fleet': (-6, 2), 'fighter_replacement': (-4, 2), 'integrated_air_defense': (-2, 2), 'yak130_trainers': (0, 2),
    'l39ng': (2, 2), 'helicopter_fleet': (4, 2), 'uav_program': (6, 2),
    'air_dominance_coast': (-3, 3),
    'air_development': (0, 6),
    'air_doctrine_reform': (0, 7), 'air_divisions': (4, 7),
    'air_superiority_ops': (-2, 8), 'air_deep_strike': (2, 8), 'air_academy': (4, 8),
    'air_layered_sam': (-2, 9), 'air_maritime_strike': (0, 9), 'air_early_warning': (2, 9), 'air_maintenance': (4, 9), 'air_transport_fleet': (6, 9),
    'air_full_spectrum': (0, 10), 'air_attack_helos': (6, 10),
    'air_hardened_airfields': (-2, 11), 'air_long_range_sam': (0, 11), 'air_awacs_patrol': (2, 11),
    'air_maritime_patrol': (-2, 12), 'air_ew': (1, 12), 'air_uav_armed': (3, 12),
    'air_superiority_wing': (-2, 13), 'air_sead': (1, 13), 'air_domestic_radar': (3, 13),
    'air_long_strike': (0, 14), 'air_alcm': (2, 14), 'air_air_2030': (4, 14),
    'air_strat_reach': (1, 15),
}
M4 = {  # defence industry + missiles (Col 4, center X = 101)
    'viettel_military_tech': (0, 1), 'russian_arms_deals': (3, 1),
    'z_factories': (0, 2),
    'licensed_rifles': (-4, 3), 'shipyards': (-2, 3), 'missile_program': (0, 3), 'defence_expo': (2, 3), 'def_industry_law': (4, 3),
    'dual_use_industry': (-3, 4), 'arms_export': (-1, 4), 'def_gdt_factories': (1, 4), 'def_viettel_hightech': (3, 4), 'def_ba_son_yard': (5, 4), 'def_vaeco_hangar': (7, 4), 'msl_coastal_home': (9, 4),
    'path_self_reliant_deterrence': (-3, 5), 'def_ammo_localisation': (0, 5), 'def_research_partnership': (2, 5), 'def_supply_chain': (4, 5), 'msl_tactical_ssm': (7, 5), 'msl_missile_defence': (9, 5),
    'def_export_growth': (3, 6), 'msl_cruise_missiles': (7, 6), 'msl_nuclear_power': (9, 6),
    'def_industry_2030': (1, 7), 'msl_dual_use_threshold': (9, 7),
    'msl_minimum_deterrent': (8, 8),
    'msl_deterrent_doctrine': (8, 9),
}
MAN = {1: M1, 2: M2, 3: M3, 4: M4}
CENTRES = {1: 59, 2: 73, 3: 87, 4: 101}
